src/fourcipp/legacy_io/element.py
As @isteinbrecher mentioned, I made the element dictionary output closer to vtu.
=> refactor: change element dictionary

src/fourcipp/legacy_io/node_topology.py, tests/fourcipp/legacy_io/test_node_topology.py
Readers and writers for * NODE-TOPOLOGY lines
=> Add node-topology reader

src/fourcipp/legacy_io/node.py, tests/fourcipp/legacy_io/test_node.py
This PR adds node io.
As seen from the code, there are more exceptions than rules. This kind of thing hints that the input is suboptimally created or that there is too much difference within a section.
=> Add node io

src/fourcipp/legacy_io/knotvectors.py, tests/fourcipp/legacy_io/test_knotvectors.py
Ok, the knotvectors parsing is absolutely crazy.
=> Add knotvector io

.github/workflows/run_testsuite.yaml, requirements.in, requirements.txt, src/fourcipp/__init__.py, src/fourcipp/fourc_input.py, src/fourcipp/legacy_io/__init__.py, src/fourcipp/legacy_io/node_topology.py, src/fourcipp/utils/validation.py, src/fourcipp/utils/yaml_io.py, tests/fourcipp/legacy_io/test_inline_dat.py, tests/fourcipp/legacy_io/test_knotvectors.py, tests/fourcipp/legacy_io/test_legacy_io.py, tests/fourcipp/legacy_io/test_node_topology.py, tests/fourcipp/test_fourc_input.py, tests/fourcipp/utils/__init__.py, tests/fourcipp/utils/test_yaml_io.py
This PR  adds an input file class to handle all the necessary details. Basically the object input generators will build upon
=> Add input file object

src/fourcipp/legacy_io/node_topology.py
=> fix: allow all DSURF and DVOL

src/fourcipp/fourc_input.py, tests/fourcipp/test_fourc_input.py
This PR adds:
- a warning if a section was overwritten
- `add` method to join either dictionaries or FourCInput file (convenience function for @davidrudlstorfer to build upon)
=> Add update from dict

README.md, tests/fourcipp/test_readme_quickstart_example.py
Update readme and add test example
=> docs: update readme

src/fourcipp/fourc_input.py, src/fourcipp/utils/dict_utils.py, src/fourcipp/utils/not_set.py, tests/fourcipp/utils/test_dict_utils.py
This PR adds basic infrastructure for input data updates. Note that this procedure does not include information about the metadata files. It only does some fancy nested dict transformations.
closes #17
=> feat: add update mechanism

.github/workflows/run_testsuite.yaml, pyproject.toml, requirements.txt, src/fourcipp/fourc_input.py, tests/fourcipp/test_readme_quickstart_example.py
=> Requirements and workflow updates

src/fourcipp/fourc_input.py, tests/fourcipp/test_fourc_input.py
After some discussion with @davidrudlstorfer  we realised that the naming join and add are somewhat misleading. There we introduce:
- 'combine_sections' which combines *entire* sections from FourCInput with a FourCInput | dict. In case the section already exists, an error is raised. This avoids overwriting
- `overwrite_sections` which overwrites *entire* sections of FourCInput from a FourCInput | dict.
=> refactor: rename join and add

src/fourcipp/legacy_io/knotvectors.py, tests/fourcipp/legacy_io/test_knotvectors.py
=> Fix knotvectors

src/fourcipp/legacy_io/knotvectors.py, tests/fourcipp/legacy_io/test_knotvectors.py
Follows https://github.com/4C-multiphysics/4C/pull/802
=> fix: update nurbs knotvectors to strings

src/fourcipp/utils/yaml_io.py
=> Use rapidyaml to dump yaml files

src/fourcipp/fourc_input.py, src/fourcipp/legacy_io/__init__.py, src/fourcipp/legacy_io/domain.py, src/fourcipp/legacy_io/element.py, src/fourcipp/legacy_io/inline_dat.py, src/fourcipp/legacy_io/knotvectors.py, src/fourcipp/legacy_io/node.py, src/fourcipp/legacy_io/node_topology.py, src/fourcipp/legacy_io/particle.py, src/fourcipp/utils/configuration.py, src/fourcipp/utils/converter.py, src/fourcipp/utils/dict_utils.py, src/fourcipp/utils/metadata.py, src/fourcipp/utils/typing.py, src/fourcipp/utils/validation.py, src/fourcipp/utils/yaml_io.py, tests/fourcipp/legacy_io/test_inline_dat.py
=> feat: add type hinting

tests/fourcipp/legacy_io/test_element.py, tests/fourcipp/legacy_io/test_particle.py, tests/fourcipp/legacy_io/utils.py
=> fix: adapt the reference element and particle creation in the tesing

src/fourcipp/legacy_io/element.py, src/fourcipp/utils/typing.py, tests/fourcipp/legacy_io/test_element.py
This PR changes the element reading to match the updates in 4C-multiphysics/4C#939
The checks will fail as long as the changes are not in the docker container yet. So by tomorrow, this should work.
=> refactor: change element reading

src/fourcipp/legacy_io/knotvectors.py
This reverts commit 315871d6e4bce72313fe7212d8114db4e2bafe4a.
=> Revert "fix: temp fix for knotvectors read in mechanism"

src/fourcipp/utils/validation.py, tests/fourcipp/utils/test_validation.py
This PR catches and identifies overflow errors before doing the schema validation.
FYI @LaSi5002
=> feat: catch overflow errors before validation

.pre-commit-config.yaml, src/fourcipp/fourc_input.py, src/fourcipp/legacy_io/element.py, src/fourcipp/legacy_io/inline_dat.py, src/fourcipp/legacy_io/knotvectors.py, src/fourcipp/utils/configuration.py, src/fourcipp/utils/converter.py, src/fourcipp/utils/dict_utils.py, src/fourcipp/utils/yaml_io.py, tests/fourcipp/legacy_io/test_particle.py, tests/fourcipp/utils/test_configuration.py
Closes #63 
- enforce type hinting across our source code
- fix type hint problems in source code
- update/fix pre-commit hook
=> Enforce and fix type hinting and update pre-commit hook

.github/workflows/run_testsuite.yaml, pyproject.toml, tests/conftest.py, tests/fourcipp/test_fourc_input.py
Added a simple performance test for core functionality of FourCInput
FYI @isteinbrecher
=> Add simple performance tests for core functionality of FourCInput

.coveragerc, .github/workflows/tag_version.yaml, .gitignore, pyproject.toml
Closes #56 
This would be the first step before we can publish our wheels on PyPI.
I think this approach is currently one of the easiest/most straightforward approaches.
@gilrrei what do you think?
FYI @isteinbrecher
=> Introduce versioning

.github/workflows/publish_pypi.yaml
=> feat: publish fourcipp to PyPI

src/fourcipp/utils/yaml_io.py, tests/fourcipp/utils/test_yaml_io.py
Follows an offline discussion with @gilrrei after #98
=> Add space after commas in vectors

requirements.in, requirements.txt
Thanks @gilrrei for the hint
I think we can also delete jsonschema?
=> refactor: cleanup requirements
